### ISSUE TITLE
Can't import requestLanguage via Typescript

### ISSUE THREAD

**Issue by nutstick** [tinganho/express-request-language#14]
I can't import `import * as requestLanguage from 'express-request-language';` when using Typescript 2.5.2. I get this error
```
[ts] Module '"/node_modules/express-request-language/index"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by tinganho** [comment]
Do you happen to know the require change?

**Comment by nutstick** [comment]
I'm not sure what you mean. Can you explain more?

**Comment by tinganho** [comment]
I was just thinking if you know the required code change to fix this issue?

**Comment by nutstick** [comment]
Ok, I will create PR to fixed it.

**Comment by tinganho** [comment]
You can just use the old import require syntax `import requestLanguage = require('express-request-language');`

**Comment by tinganho** [comment]
Seems like you cannot use the import assignment syntax if you target es2015 modules.
The required fix for it seems to be:
```ts
declare namespace requestLanguage { }
```
So now you can do:
```ts
import * as requestLanguage from 'express-request-language';
```
I updated the lib now, so you can use the above syntax.

**Comment by nutstick** [comment]
Wow! thanks for an update.
