### ISSUE TITLE
Unset language

### ISSUE THREAD

**Issue by ericelliott** [tinganho/express-request-language#3]
We need a way to unset the language for testing.

**Comment by tinganho** [comment]
I'm not sure I'm convinced this is needed? What prevents you from calling `res.clearCookie` directly instead of navigating to a URL? And if you want a URL, you can just implement a URL endpoint for resetting the language cookie quite easy.

Can you describe your testing scenario?

**Comment by ericelliott** [comment]
=)

The testing scenario is that QA teams and developers should be able to easily and arbitrarily _set and unset_ the language in _testing and production environments_.

Yes, I agree it's easy to implement an unset route manually, but libraries exist so the every project doesn't have to reinvent the wheel.

_We provide a way to set the language cookie, but not unset it?_ So every project that uses this has to implement an unset route manually? The way I determine what does and doesn't belong in a library is the _principle of high cohesion_. If the functionality is strongly cohesive with the rest of the library, and it's something that most consumers of the library will need, that makes it a strong candidate to _add to the library_.

I could implement an unset middleware in Keystone, but IMO, _this library is not complete without an unset mechanism_.

**Comment by tinganho** [comment]
After thinking about it again it seems reasonable to add it. Just let me sleep on it in a day or so, I want to be sure that I don't make any mistake on this.

**Comment by ericelliott** [comment]
Cool. In the meantime, I'm prepping to integrate into Keystone right now. =)

**Comment by tinganho** [comment]
The changes you made are now published in `express-request-language@1.1.0`.

**Comment by tinganho** [comment]
Thanks again @ericelliott

**Comment by ericelliott** [comment]
Thank you. Great job on this lib. =)
